### ISSUE TITLE
Не входит в режим прошивки

### ISSUE THREAD

**Issue by suprimex** [esnet146/mini-smart-switch2#1]
Такое же реле, чип от Belon BL2028N, не входит в режим прошивки. Что бы я не делал, питание передергивал, 100500 раз чип ресетил через CEN , модуль просто заускается в штатном режиме и все. Пробовал и Win-прошивальшик, и Python утилиту. UART проверял (замыкал TX и RX, связь есть.)

**Comment by esnet146** [comment]
подключитесь к uart порту терминалом. Должен быть лог загрузки. Вы его видите? Если нет лога - вы неправильно или не туда подключили uart преобразователь.

**Comment by esnet146** [comment]
нет ответов -нет решения
